// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type UnsafeAny = unknown

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & Record<string, UnsafeAny>> | ((props: { params: Promise<ParamMap[Route]> } & Record<string, UnsafeAny>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<UnsafeAny[]> | UnsafeAny[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, UnsafeAny>,
    parent: ResolvingMetadata
  ) => Promise<UnsafeAny> | UnsafeAny
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, UnsafeAny>,
    parent: ResolvingViewport
  ) => Promise<UnsafeAny> | UnsafeAny
  metadata?: UnsafeAny
  viewport?: UnsafeAny
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<UnsafeAny[]> | UnsafeAny[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, UnsafeAny>,
    parent: ResolvingMetadata
  ) => Promise<UnsafeAny> | UnsafeAny
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, UnsafeAny>,
    parent: ResolvingViewport
  ) => Promise<UnsafeAny> | UnsafeAny
  metadata?: UnsafeAny
  viewport?: UnsafeAny
}


// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
